### ISSUE TITLE
Support exploring any repo

### ISSUE THREAD

**Issue by gardenofwine** [scriptit/github-api-gui#1]
It seems that currently the only supported organization is "scriptit" (even when I install this on my own machine).

It would be great to be able to select which repo you want to explore (and even support a different github url - to support hosted enterprise github servers)

**Comment by ForbesLindesay** [comment]
You can edit any of these values, they're all in text boxes.  If that's not working, perhaps it's a browser issue.  What web browser are you using?

**Comment by ForbesLindesay** [comment]
I've tested in:
- Chrome
- Firefox
- Safari

on a mac, and all seem to work fine.

**Comment by gardenofwine** [comment]
ooops, I totally missed that textedit box on the page.
